### ISSUE TITLE
Prod -- Getting a blank screen when try to sign up from Lock&Key, Beagle, and Drive

### ISSUE THREAD

**Issue by sunqaanalyst** [vinli/android-net#29]
When try to do a sign up by clicking on "No Account? Sign up now for free!" link from all three Lock&Key, Beagle, and Drive apps, getting a blank screen.  NOTE:  getting the sign in screen NOT the sign up screen if rotate the mobile from vertical to horizontal mode.

Drive V1.0 (10)
Beagle V1.0b (10)
Lock & Key V1.0b (2)

![screenshot_2015-10-16-18-35-54](https://cloud.githubusercontent.com/assets/13627817/10555452/3da19730-7435-11e5-8921-a0e5f92c052f.png)
![screenshot_2015-10-16-18-36-40](https://cloud.githubusercontent.com/assets/13627817/10555451/3d9f77ac-7435-11e5-8b6d-7448d8f26518.png)

**Comment by cmc5788** [comment]
fixed in the following build numbers: Lock and Key 5, Beagle 11, Drive 11

**Comment by sunqaanalyst** [comment]
Verified in Drive V1.0 (12)
Beagle V1.0b (11)
Lock & Key V1.0b (5)
