### ISSUE TITLE
How to call getTrip method??

### ISSUE THREAD

**Issue by ashababu** [vinli/android-net#39]
After getting device Id ,how to get the trips?

**Comment by tommista** [comment]
Hey, if all you have is a device id, you will need to get a Device object first before you can get a list of trips. Below is a bit of code that should help you work through all that. 

`// You get a VinliApp by going through the OAuth flow
    vinliApp.device("Your device id").subscribe(new Subscriber<Device>() {
      @Override
      public void onCompleted() {

      }

      @Override
      public void onError(Throwable e) {

      }

      @Override
      public void onNext(Device device) {
        device.trips().subscribe(new Subscriber<Page<Trip>>() {
          @Override
          public void onCompleted() {

          }

          @Override
          public void onError(Throwable e) {

          }

          @Override
          public void onNext(Page<Trip> tripPage) {

          }
        });
      }
    });`
