### ISSUE TITLE
How to get the coordinates(lat,long) from the TripList?

### ISSUE THREAD

**Issue by ashababu** [vinli/android-net#43]
I am calling Trip from vinli SDK. But I didn't get the coordinates from the Trip details array. How will I handle this?

**Comment by shayneo** [comment]
Trips are composed of many Telemetry messages and thus many Locations (lat/long coordinates).  There are a couple of ways to access locations for a trip.

If you want to know the trip's starting and stoping location, you can find these in the Trip object... `startPoint` and `stopPoint`.

**Comment by ashababu** [comment]
yea.I added Vinli gradle,But the startPoint and stopPoint objects are not there in Trip model class. But the startPoint and stopPoint is there in the Trip model class of Vinli android.net module.

**Comment by tommista** [comment]
What version of the Vinli SDK are you using? The latest version is 1.0.17

**Comment by cmc5788** [comment]
Old and resolved for quite some time. Closing.
