### ISSUE TITLE
Use retrofit2 and okhttp3

### ISSUE THREAD

**Issue by code4android** [vinli/android-net#49]
Can you adopt the last versions of both libraries?

**Comment by sandro-csimas** [comment]
It will be nice to upgrade okhttp. I'm having problems with NewRelic.

**Comment by cmc5788** [comment]
This is in the cards and should be available relatively soon.

**Comment by dofchinick** [comment]
Moved to vinli/platform#667

**Comment by cmc5788** [comment]
Closed by https://github.com/vinli/android-net/pull/59
