### ISSUE TITLE
Vehicle bean

### ISSUE THREAD

**Issue by McTALAO** [vinli/android-net#63]
The vehicle class doesn't contain all data that we can retrieve from api.
For example "data" and "lastStartup" aren't mapped in the Vehicle class.

`{
    "vehicles": [{
        "id": "14eb950d-0597-49a6-a44b-84b331299e6a",
        "vin": "XXXXX7CEC796E5C53",
        "make": null,
        "model": null,
        "year": null,
        "trim": null,
        "data": {
            "engine": null,
            "engineDisplacement": null,
            "transmission": null,
            "manufacturer": null,
            "categories": null,
            "epaMpg": null,
            "drive": null,
            "numDoors": null
        },
        "createdAt": "2016-04-08T13:37:24.520Z",
        "links": {
            "self": "https://platform.vin.li/api/v1/vehicles/14eb950d-0597-49a6-a44b-84b331299e6a",
            "trips": "https://trips.vin.li/api/v1/vehicles/14eb950d-0597-49a6-a44b-84b331299e6a/trips",
            "codes": "https://diagnostic.vin.li/api/v1/vehicles/14eb950d-0597-49a6-a44b-84b331299e6a/codes",
            "collisions": "https://safety.vin.li/api/v1/vehicles/14eb950d-0597-49a6-a44b-84b331299e6a/collisions"
        },
        "lastStartup": "2016-10-06T05:46:39.177Z"
    },`

**Comment by cmc5788** [comment]
Thanks for reporting this, we'll take a look and update the model shortly.

**Comment by cmc5788** [comment]
Closed by #71
