### ISSUE TITLE
Device Bean

### ISSUE THREAD

**Issue by McTALAO** [vinli/android-net#68]
The **Device class** ([https://github.com/vinli/android-net/blob/master/android-net/src/main/java/li/vin/net/Device.java](https://github.com/vinli/android-net/blob/master/android-net/src/main/java/li/vin/net/Device.java)) doesn't contain all data that we can retrieve from api.
For example "caseId" isn't mapped in the Device class.

`{
	"devices": [{
		"id": "3d7ab2a2-50c2-44e2-bed7-6f1ee5f0687d",
		"name": "Ffhc",
		"icon": null,
		"createAt": "2016-08-22T08:28:07.200Z",
		"updatedAt": "2016-08-22T08:28:07.200Z",
		"caseId": "VVCC3MM",
		"chipId": "VV6E8BDE6128",
		"providerId": "953bf983-481f-4b96-b56e-62fb1863801f",
		"dataPlanId": null,
		"nextDataPlanId": null,
		"nextBillingAt": null,
		"trialPlanId": null,
		"trialEndsAt": null,
		"links": {
			"contacts": "/api/v1/devices/3d7ab2a2-50c2-44e2-bed7-6f1ee5f0687d/contacts",
			"wifiSetting": "/api/v1/wifiSettings/3d7ab2a2-50c2-44e2-bed7-6f1ee5f0687d",
			"wifiUsage": "/api/v1/devices/3d7ab2a2-50c2-44e2-bed7-6f1ee5f0687d/wifiUsage"
		},
		"latestVehicle": {
			"id": "b0fb429d-c3c6-46e2-a5fa-6730f80c0a0e",
			"vin": "VVXBJ2LF18GRM3P2J",
			"make": "Virtual Vinli",
			"model": "Mach Five",
			"year": "1967",
			"trim": "2dr Coupé",
			"lastStartup": null,
			"metadata": "{}",
			"infoUpdatedAt": "2016-10-20T12:42:31.611Z",
			"infoUpdateStatus": "success",
			"createdAt": "2016-10-20T12:42:28.003Z",
			"updatedAt": "2016-10-20T12:42:31.621Z"
		}
	}],
	"meta": {
		"pagination": {
			"total": 1,
			"limit": 50,
			"offset": 0,
			"links": {
				"first": "http://auth-1.2.0-5425-177f264-308194302-f3cf9:3000/api/v1/_internal/devices?offset=0&limit=50",
				"last": "http://auth-1.2.0-5425-177f264-308194302-f3cf9:3000/api/v1/_internal/devices?offset=0&limit=50"
			}
		}
	}
}`

**Comment by cmc5788** [comment]
We only return the information documented at docs.vin.li - it looks like you've got JSON for our user-facing My Vinli application, which isn't intended as a general-purpose developer focused API. Closing.
