### ISSUE TITLE
DTCS - Filter by "status"

### ISSUE THREAD

**Issue by McTALAO** [vinli/android-net#74]
I noticed that the call for DTC (`pubblic Observable<TimeSeries<Dtc>> dtcs(@Nullable @Query("since") Long since, @Nullable @Query("until") Long until, @Nullable @Query("limit") Integer limit, @Nullable Query("sortDir") String sortDir)`) does not allow you to filter by the "state" ("active" or "inactive").

REF: `curl -k -X GET -H "Content-Type:application/json" -H "Authorization: Bearer ---" https://diagnostic.vin.li/api/v1/vehicles/---/codes?state=active`

**Comment by cmc5788** [comment]
closed by https://github.com/vinli/android-net/pull/78
