### ISSUE TITLE
Vehicle - Wrong Year

### ISSUE THREAD

**Issue by McTALAO** [vinli/android-net#77]
The "year" (li.vin.net.Vehicle bean) field sometimes returns the wrong value: `"year": "10th character in VIN code is<br>not recognized (U, Z and 0)."`

`{
		"id": "5dd26d2c-103b-4026-867c-064b128613e6",
		"vin": "WBAUD910X0P379389",
		"make": "BMW",
		"model": null,
		"year": "10th character in VIN code is<br>not recognized (U, Z and 0).",
		"trim": null,
		"data": {
			"engine": null,
			"engineDisplacement": null,
			"transmission": null,
			"manufacturer": null,
			"categories": null,
			"epaMpg": null,
			"drive": null,
			"numDoors": null
		},
		"createdAt": "2016-04-15T18:00:24.837Z",
		"links": {
			"self": "https://platform.vin.li/api/v1/vehicles/5dd26d2c-103b-4026-867c-064b128613e6",
			"trips": "https://trips.vin.li/api/v1/vehicles/5dd26d2c-103b-4026-867c-064b128613e6/trips",
			"codes": "https://diagnostic.vin.li/api/v1/vehicles/5dd26d2c-103b-4026-867c-064b128613e6/codes",
			"collisions": "https://safety.vin.li/api/v1/vehicles/5dd26d2c-103b-4026-867c-064b128613e6/collisions"
		},
		"lastStartup": "2016-12-06T08:43:54.234Z"
	}`

**Comment by shayneo** [comment]
@cmc5788 can you take a look at this vehicle ID and see what's up?

**Comment by cmc5788** [comment]
yep. Seems like there's some platform work needed here, going to look into it. Will likely be a sprint or so off from a fix.

@McTALAO - in the mean time, I'd suggest some clientside sanity checks on values returned for the vehicle model.

**Comment by shayneo** [comment]
Thanks @cmc5788 

@McTALAO - do you happen to know the actual specs of the vehicle? This will be helpful for us to diagnose the issue.

**Comment by McTALAO** [comment]
@cmc5788 Ok, thank you.

@shayneo The correct year is 2011.
For more details: [http://www.etkbmw.com/bmw/IT/vin/decoder/WBAUD910X0P379389/IT/](http://www.etkbmw.com/bmw/IT/vin/decoder/WBAUD910X0P379389/IT/)

**Comment by cmc5788** [comment]
Closed by backend updates to sanitize make / model / year.
