### ISSUE TITLE
JCenter - Version 1.0.42

### ISSUE THREAD

**Issue by McTALAO** [vinli/android-net#79]
Hi, on JCenter ([https://bintray.com/vinli/li.vin/android-net](https://bintray.com/vinli/li.vin/android-net)) I do not see the latest version 1.0.42 ([https://github.com/vinli/android-net/blob/master/gradle.properties](https://github.com/vinli/android-net/blob/master/gradle.properties)).
Could you publish this latest version?

**Comment by cmc5788** [comment]
Closed by `1.0.42` tagged, bintray uploaded on 0c4bf22c7840cc22f45ef17547c95abebe3dd0e6
